# Generated by Django 4.2.11 on 2024-11-28 16:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('resume', models.FileField(upload_to='personal/resume', verbose_name='resume')),
            ],
            options={
                'verbose_name': 'PersonalInfo',
                'verbose_name_plural': 'PersonalInfos',
            },
        ),
        migrations.CreateModel(
            name='PersonalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='percentage')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personalinfo')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technology')),
            ],
            options={
                'verbose_name': 'PersonalSkill',
                'verbose_name_plural': 'PersonalSkills',
            },
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='skills',
            field=models.ManyToManyField(through='core.PersonalSkill', to='core.technology'),
        ),
    ]
