# Generated by Django 4.2.11 on 2024-11-28 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_personalinfo_personalskill_personalinfo_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='date_upd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='statut',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personalskill',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalskill',
            name='date_upd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='personalskill',
            name='statut',
            field=models.BooleanField(default=True),
        ),
    ]
